apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJnaGNyLmlvIjogewoJCQkiYXV0aCI6ICJZVzUwYjI1ZlpHOXNaMkZ1WlhZNloyaHdYMWt5YUdWWmJtTmpRVXRzY0ROVWFVaDNaVUkyTUZoS1dHUTBhR2xKWXpGNk1FeGxSdz09IgoJCX0KCX0KfQ==
type: kubernetes.io/dockerconfigjson
